spring:
  application:
    name: tvseries-service
  datasource:
    password: postgres
    url: jdbc:postgresql://localhost:5432/db_tvserie
    username: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
server:
  port: 8082