version: '3.8'

services:
  rabbitmq:
    image: rabbitmq
    container_name: 'rabbitmq_server'
    ports:
      - "5672:5672"
      - "15672:15672"
  postgres_keycloak:
    image: postgres
    container_name: keycloak_data
    volumes:
      - keycloak_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
  keycloak:
    image: quay.io/keycloak/keycloak:legacy
    container_name: keycloak_server
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres_keycloak
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Pa55w0rd
    ports:
      - "5555:8080"
    depends_on:
      - postgres_keycloak
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    container_name: zookeeper_server
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:latest'
    container_name: kafka_server
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin_server
    ports:
      - '9411:9411'
  config_service:
    build:
      context: ./config-service
      dockerfile: Dockerfile
    container_name: config_service
    ports:
      - '7777:7777'
  discovery_service:
    build:
      context: ./discovery-service
      dockerfile: Dockerfile
    container_name: discovery_service
    ports:
      - '8888:8888'
    depends_on:
      - config_service
  gateway_service:
    build:
      context: ./gateway-service
      dockerfile: Dockerfile
    container_name: gateway_service
    ports:
      - '9999:9999'
    depends_on:
      - config_service
      - discovery_service
  postgres_comment_service:
    image: postgres
    container_name: comment_data
    volumes:
      - comment_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: db_comment
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  comment_service:
    build:
      context: ./comment-service
      dockerfile: Dockerfile
    container_name: comment_service
    ports:
      - '8083:8083'
    depends_on:
      - gateway_service
      - postgres_comment_service
      - kafka
      - rabbitmq
      - keycloak
      - zipkin
  postgres_movie_service:
    image: postgres
    container_name: movie_data
    volumes:
      - movie_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: db_movie
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  movie_service:
    build:
      context: ./movie-service
      dockerfile: Dockerfile
    container_name: movie_service
    ports:
      - '8081:8081'
    depends_on:
      - gateway_service
      - postgres_movie_service
      - kafka
      - rabbitmq
      - keycloak
      - zipkin
  postgres_rating_service:
    image: postgres
    container_name: rating_data
    volumes:
      - rating_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: db_rating
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  rating_service:
    build:
      context: ./rating-service
      dockerfile: Dockerfile
    container_name: rating_service
    ports:
      - '8085:8085'
    depends_on:
      - gateway_service
      - postgres_rating_service
      - kafka
      - rabbitmq
      - keycloak
      - zipkin
  postgres_tv_series_service:
    image: postgres
    container_name: tv_data
    volumes:
      - tv_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: db_tvseries
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  tv_service:
    build:
      context: ./tvseries-service
      dockerfile: Dockerfile
    container_name: tvseries_service
    ports:
      - '8082:8082'
    depends_on:
      - gateway_service
      - postgres_tv_series_service
      - kafka
      - rabbitmq
      - keycloak
      - zipkin
  postgres_user_service:
    image: postgres
    container_name: user_data
    volumes:
      - user_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: db_user
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  user_service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    container_name: user_service
    ports:
      - '8084:8084'
    depends_on:
      - gateway_service
      - postgres_user_service
      - kafka
      - rabbitmq
      - keycloak
      - zipkin
