spring:
  rabbitmq:
    host: localhost
    port: 5672
    password: guest
    username: guest
  application:
    name: movie-service
  datasource:
    password: 12345
    url: jdbc:postgresql://localhost:5001/db_movie
    username: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
server:
  port: 8081
